# Generated by Django 5.0.6 on 2024-08-30 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_remove_student_gender_student_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='Not Specify', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('I', 'Islam'), ('C', 'Christian')], default='Unknown Religion', max_length=50),
        ),
    ]
