# Generated by Django 5.0.6 on 2024-08-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_gender_alter_student_religion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='Not Specify', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='nationality',
            field=models.CharField(choices=[('Nigeria', 'nigeria'), ('Non Nigeria', 'non nigeria')], default='Unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='religion',
            field=models.CharField(choices=[('Islam', 'Islam'), ('Christian', 'Christian')], default='Unknown Religion', max_length=50),
        ),
    ]
